/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ReturnBook;

import IssueBook.*;
import Reader.*;
import Book.*;
import BookDetail.*;
import Bill.*;
import BillDetail.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hảii Dươnq
 */
public class ReturnBookView extends javax.swing.JInternalFrame {

    DefaultTableModel model;
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

    List<Reader> lstReader;
    Reader reader;
    ReaderManager readerManager;

    List<Bill> lstBill;
    Bill bill;
    BillManager billManager;

    List<BillDetail> lstBillDetail;
    BillDetail billD;
    BillDetailManager billDetailManager;

    List<Book> lstBook;
    Book book;
    BookManager bookManager;

    List<BookDetail> lstBookDetail;
    BookDetail bookDetail;
    BookDetailManager bookDetailManager;

    /**
     * Creates new form CategoryView
     */
    public ReturnBookView() {
        initComponents();
        readerManager = new ReaderManager();
        billManager = new BillManager();
        billDetailManager = new BillDetailManager();
        bookManager = new BookManager();
        bookDetailManager = new BookDetailManager();
        SetDateNow();
        getCbox();
    }

    public void SetDateNow() {
        LocalDate dateNow = LocalDate.now();
        try {
            DateReturn.setDate(dateFormat.parse(String.valueOf(dateNow)));
        } catch (ParseException ex) {
            Logger.getLogger(ReturnBookView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void getCbox() {
        lstBook = bookManager.getAllBook();
        for (Book b : lstBook) {
            cboNameBook.addItem(b.getName());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cboNameBook = new javax.swing.JComboBox<>();
        jPanel16 = new javax.swing.JPanel();
        txtNameReader = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        DateReturn = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setPreferredSize(new java.awt.Dimension(1632, 585));

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 35));
        jPanel2.setLayout(new java.awt.CardLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Management Issue Book");
        jLabel3.setToolTipText("");
        jPanel2.add(jLabel3, "card2");

        jPanel1.add(jPanel2);

        jPanel3.setName(""); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 315));

        jPanel10.setPreferredSize(new java.awt.Dimension(350, 65));
        jPanel10.setRequestFocusEnabled(false);
        jPanel10.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Name Book:");
        jLabel4.setPreferredSize(new java.awt.Dimension(42, 25));
        jPanel10.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        jPanel10.add(cboNameBook, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel10);

        jPanel16.setPreferredSize(new java.awt.Dimension(350, 65));
        jPanel16.setRequestFocusEnabled(false);
        jPanel16.setLayout(new java.awt.BorderLayout(4, 4));

        txtNameReader.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNameReader.setForeground(new java.awt.Color(255, 0, 0));
        txtNameReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameReaderActionPerformed(evt);
            }
        });
        jPanel16.add(txtNameReader, java.awt.BorderLayout.CENTER);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Name Reader:");
        jLabel9.setPreferredSize(new java.awt.Dimension(42, 25));
        jPanel16.add(jLabel9, java.awt.BorderLayout.PAGE_START);

        jPanel3.add(jPanel16);

        jPanel12.setPreferredSize(new java.awt.Dimension(350, 65));
        jPanel12.setRequestFocusEnabled(false);
        jPanel12.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Phone :");
        jLabel6.setPreferredSize(new java.awt.Dimension(45, 25));
        jPanel12.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        txtPhone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(255, 0, 0));
        jPanel12.add(txtPhone, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel12);

        jPanel11.setPreferredSize(new java.awt.Dimension(350, 65));
        jPanel11.setRequestFocusEnabled(false);
        jPanel11.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Date Return :");
        jLabel5.setPreferredSize(new java.awt.Dimension(42, 25));
        jPanel11.add(jLabel5, java.awt.BorderLayout.PAGE_START);
        jPanel11.add(DateReturn, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel11);

        jPanel1.add(jPanel3);

        jPanel4.setPreferredSize(new java.awt.Dimension(712, 50));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("Return Book");
        btnAdd.setMinimumSize(new java.awt.Dimension(140, 25));
        btnAdd.setPreferredSize(new java.awt.Dimension(140, 30));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel4.add(btnAdd);

        jPanel1.add(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String nameR = txtNameReader.getText();
        String phone = txtPhone.getText();

        if (nameR.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Name");
            return;
        } else if (nameR.length() >= 64) {
            JOptionPane.showMessageDialog(this, "Name Length Must Be Less Than 64 Characters");
            return;
        } else if (phone.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Phone");
            return;
        }

        String nameB = (String) cboNameBook.getSelectedItem();
        if (nameB.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Name");
            return;
        } else if (nameB.length() >= 64) {
            JOptionPane.showMessageDialog(this, "Name Length Must Be Less Than 64 Characters");
            return;
        }

        LocalDate DateR = null;
        try {
            String dreturn = dateFormat.format(DateReturn.getDate());
            DateR = LocalDate.parse(dreturn, DateTimeFormatter.ISO_DATE);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Enter Date !");
            return;
        }

        //ID Reader
        lstReader = readerManager.getNamePhoneReader(nameR, phone);

        lstBook = bookManager.getOneBook(nameB);
        if (lstReader.size() == 0 || lstBook.size() == 0) {
            JOptionPane.showMessageDialog(this, "Bill Does Not Exit !");
            return;
        } else {
            int ID_Reader = 0;
            for (Reader r : lstReader) {
                ID_Reader = r.getId();
            }
            int Id_Bill = 0;
            lstBill = billManager.getOneBill(ID_Reader);
            for (Bill bill1 : lstBill) {
                Id_Bill = bill1.getId();
            }
            // Id BookDetail
            int id_Book = 0, Id_BookDetail = 0, QuantityRemain = 0;
            lstBookDetail = bookDetailManager.getAllBookDetail();
            for (Book b : lstBook) {
                QuantityRemain = b.getQuantityRemain();
                id_Book = b.getId();
                for (BookDetail bd : lstBookDetail) {
                    if (b.getId() == bd.getId_Book()) {
                        Id_BookDetail = bd.getId();
                    }
                }
            }

            //Id BillDetail
            int Id_BillDetail = 0;
            lstBillDetail = billDetailManager.getAllBillDetail();
            for (BillDetail billDetail : lstBillDetail) {
                if (billDetail.getId_Bill() == Id_Bill && billDetail.getId_BookDetail() == Id_BookDetail) {
                    Id_BillDetail = billDetail.getId();
                }
            }

            boolean Status = false;
            BillDetail billDetail = new BillDetail(Id_BillDetail, DateR, Status);
            int bds = billDetailManager.ReturnBillDetail(billDetail);

            if (bds > 0) {
                QuantityRemain += 1;
                Book bqtt = new Book(id_Book, QuantityRemain);
                int updateQuantity = bookManager.UpdateQuantityRemainBook(bqtt);

                if (updateQuantity > 0) {
                    JOptionPane.showMessageDialog(this, "Return Book Success !");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Return Book Error !", "Inane error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtNameReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameReaderActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNameReaderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateReturn;
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox<String> cboNameBook;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtNameReader;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables

}
