/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Book;

import BookDetail.*;
import Author.*;
import Publisher.*;
import Translator.*;
import TypeBook.*;
import TypeBook.Type;
import TypeBook.TypeManager;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Hảii Dươnq
 */
public class BookDetailView extends javax.swing.JDialog {

    /**
     * Creates new form BookDetailView
     */
    public BookDetailView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
    }
    
    public void setData(Book book) {
        lblId.setText(String.valueOf(book.getId()));
        lblName.setText(book.getName());
        
        BookDetailManager bookDetailMa = new BookDetailManager();
        
        List<BookDetail> lstDetail = new ArrayList<BookDetail>();
        bookDetailMa = new BookDetailManager();
        lstDetail = bookDetailMa.getAllBookDetail();
        
        List<BookDetail> lstAuthorDetail = new ArrayList<BookDetail>();
        bookDetailMa = new BookDetailManager();
        lstAuthorDetail = bookDetailMa.getListAuthorDetail(book.getId());
        
        List<BookDetail> lstTypeDetail = new ArrayList<BookDetail>();
        bookDetailMa = new BookDetailManager();
        lstTypeDetail = bookDetailMa.getListTypeDetail(book.getId());
        
        List<Author> lstAuthor = new ArrayList<Author>();
        AuthorManager AM = new AuthorManager();
        lstAuthor = AM.getAllAuthor();
        
        List<Publisher> lstPublisher = new ArrayList<Publisher>();
        PublisherManager PM = new PublisherManager();
        lstPublisher = PM.getAllPublisher();
        
        List<Translator> lstTrans = new ArrayList<Translator>();
        TranslatorManager TrM = new TranslatorManager();
        lstTrans = TrM.getAllTranslator();
        
        List<TypeBook.Type> lstType = new ArrayList<TypeBook.Type>();
        TypeManager TM = new TypeManager();
        lstType = TM.getAllType();
        
        for (BookDetail bookAuDetail : lstAuthorDetail) {
            for (int i = 0; i < lstAuthor.size(); i++) {
                if (bookAuDetail.getId_Author() == lstAuthor.get(i).getId()) {
                    if (i == 0) {
                        lblAuthor.setText(lblAuthor.getText() + lstAuthor.get(i).getName());
                    } else {
                        
                        lblAuthor.setText(lblAuthor.getText() + ", " + lstAuthor.get(i).getName());
                    }
                }
            }
        }
        
        for (BookDetail bookTyDetail : lstTypeDetail) {
            for (int i = 0; i < lstType.size(); i++) {
                if (bookTyDetail.getId_Type() == lstType.get(i).getId()) {
                    if (i == 0) {
                        lblType.setText(lblType.getText() + lstType.get(i).getName());
                    } else {
                        lblType.setText(lblType.getText() + ", " + lstType.get(i).getName());
                    }
                }
            }
        }
        
        for (BookDetail bookDetail : lstDetail) {
            if (bookDetail.getId_Book() == book.getId()) {
                
                for (Publisher publisher : lstPublisher) {
                    if (bookDetail.getId_Publisher() == publisher.getId()) {
                        lblPublisher.setText(publisher.getName());
                    }
                }
                for (Translator trans : lstTrans) {
                    if (bookDetail.getId_Translator() == trans.getId()) {
                        lblTranlator.setText(trans.getName());
                    }
                }
                
            }
        }
        lblPrice.setText(String.valueOf(book.getPrice()));
        lblQuantity.setText(String.valueOf(book.getQuantity()));
        lblQuantityRe.setText(String.valueOf(book.getQuantity()));
        lblDateAdd.setText(book.getDateAdded().toString());
        lblDes.setText(book.getDescription());
        if (book.isStatus() == true) {
            lblStatus.setText("Show");
        } else {
            lblStatus.setText("Hidden");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblPublisher = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblTranlator = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lblQuantityRe = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        lblDateAdd = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        lblDes = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 800));
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(450, 50));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Book Detail");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(450, 620));

        jPanel4.setPreferredSize(new java.awt.Dimension(350, 35));
        jPanel4.setRequestFocusEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Id :");
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel4.add(jLabel2);

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 0, 0));
        lblId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblId.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel4.add(lblId);

        jPanel2.add(jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(350, 80));
        jPanel5.setRequestFocusEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Name");
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel5.add(jLabel4);

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 0, 0));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setPreferredSize(new java.awt.Dimension(350, 30));
        jPanel5.add(lblName);

        jPanel2.add(jPanel5);

        jPanel6.setPreferredSize(new java.awt.Dimension(450, 35));
        jPanel6.setRequestFocusEnabled(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Author :");
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel6.add(jLabel6);

        lblAuthor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAuthor.setForeground(new java.awt.Color(255, 0, 0));
        lblAuthor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAuthor.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel6.add(lblAuthor);

        jPanel2.add(jPanel6);

        jPanel7.setPreferredSize(new java.awt.Dimension(350, 35));
        jPanel7.setRequestFocusEnabled(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Publisher :");
        jLabel8.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel7.add(jLabel8);

        lblPublisher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPublisher.setForeground(new java.awt.Color(255, 0, 0));
        lblPublisher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPublisher.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel7.add(lblPublisher);

        jPanel2.add(jPanel7);

        jPanel8.setPreferredSize(new java.awt.Dimension(350, 35));
        jPanel8.setRequestFocusEnabled(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Tranlator :");
        jLabel10.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel8.add(jLabel10);

        lblTranlator.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTranlator.setForeground(new java.awt.Color(255, 0, 0));
        lblTranlator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTranlator.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel8.add(lblTranlator);

        jPanel2.add(jPanel8);

        jPanel9.setPreferredSize(new java.awt.Dimension(350, 35));
        jPanel9.setRequestFocusEnabled(false);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Type Book :");
        jLabel12.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel9.add(jLabel12);

        lblType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblType.setForeground(new java.awt.Color(255, 0, 0));
        lblType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblType.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel9.add(lblType);

        jPanel2.add(jPanel9);

        jPanel10.setPreferredSize(new java.awt.Dimension(350, 35));
        jPanel10.setRequestFocusEnabled(false);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Price :");
        jLabel14.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel10.add(jLabel14);

        lblPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(255, 0, 0));
        lblPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrice.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel10.add(lblPrice);

        jPanel2.add(jPanel10);

        jPanel11.setPreferredSize(new java.awt.Dimension(350, 35));
        jPanel11.setRequestFocusEnabled(false);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Quantity :");
        jLabel16.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel11.add(jLabel16);

        lblQuantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQuantity.setForeground(new java.awt.Color(255, 0, 0));
        lblQuantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantity.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel11.add(lblQuantity);

        jPanel2.add(jPanel11);

        jPanel12.setPreferredSize(new java.awt.Dimension(350, 35));
        jPanel12.setRequestFocusEnabled(false);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Quantity Remain :");
        jLabel18.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel12.add(jLabel18);

        lblQuantityRe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQuantityRe.setForeground(new java.awt.Color(255, 0, 0));
        lblQuantityRe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuantityRe.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel12.add(lblQuantityRe);

        jPanel2.add(jPanel12);

        jPanel13.setPreferredSize(new java.awt.Dimension(350, 35));
        jPanel13.setRequestFocusEnabled(false);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Date Add :");
        jLabel20.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel13.add(jLabel20);

        lblDateAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDateAdd.setForeground(new java.awt.Color(255, 0, 0));
        lblDateAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDateAdd.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel13.add(lblDateAdd);

        jPanel2.add(jPanel13);

        jPanel14.setPreferredSize(new java.awt.Dimension(350, 100));
        jPanel14.setRequestFocusEnabled(false);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Description :");
        jLabel22.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel14.add(jLabel22);

        lblDes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDes.setForeground(new java.awt.Color(255, 0, 0));
        lblDes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblDes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDes.setMaximumSize(new java.awt.Dimension(350, 100));
        lblDes.setMinimumSize(new java.awt.Dimension(350, 100));
        lblDes.setName(""); // NOI18N
        lblDes.setOpaque(true);
        lblDes.setPreferredSize(new java.awt.Dimension(350, 50));
        lblDes.setRequestFocusEnabled(false);
        jPanel14.add(lblDes);

        jPanel2.add(jPanel14);

        jPanel15.setPreferredSize(new java.awt.Dimension(350, 35));
        jPanel15.setRequestFocusEnabled(false);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Status :");
        jLabel24.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel15.add(jLabel24);

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 0, 0));
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel15.add(lblStatus);

        jPanel2.add(jPanel15);

        getContentPane().add(jPanel2);

        jPanel3.setPreferredSize(new java.awt.Dimension(350, 50));

        btnClose.setText("Close");
        btnClose.setPreferredSize(new java.awt.Dimension(125, 35));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel3.add(btnClose);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookDetailView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookDetailView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookDetailView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookDetailView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BookDetailView dialog = new BookDetailView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblDateAdd;
    private javax.swing.JLabel lblDes;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblPublisher;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblQuantityRe;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTranlator;
    private javax.swing.JLabel lblType;
    // End of variables declaration//GEN-END:variables
}
