/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package HomeLibrary;

import Author.AuthorView;
import Book.BookView;
import IssueBook.*;
import CategoryBook.CategoryView;
import Publisher.PublisherView;
import Reader.ReaderView;
import ReturnBook.ReturnBookView;
import Static.StaticView;
import Translator.TranslatorView;
import TypeBook.TypeView;
import javax.swing.JFrame;

/**
 *
 * @author Hảii Dươnq
 */
public class Home extends javax.swing.JFrame {

    /** Creates new form Home */
    public Home() {
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeskPHome = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        IssueBook = new javax.swing.JButton();
        btnReturnBook = new javax.swing.JButton();
        btnStatic = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuManagerReader = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        MItemManageCategory = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuManageAuthor = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuManagerTranslator = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuManagerPublisher = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuManageType = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Library");

        javax.swing.GroupLayout DeskPHomeLayout = new javax.swing.GroupLayout(DeskPHome);
        DeskPHome.setLayout(DeskPHomeLayout);
        DeskPHomeLayout.setHorizontalGroup(
            DeskPHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1016, Short.MAX_VALUE)
        );
        DeskPHomeLayout.setVerticalGroup(
            DeskPHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 75));

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 0, 0));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/group.png"))); // NOI18N
        jButton8.setText("Add Reader");
        jButton8.setPreferredSize(new java.awt.Dimension(200, 65));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 0, 0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/medical-book.png"))); // NOI18N
        jButton9.setText("New Book");
        jButton9.setPreferredSize(new java.awt.Dimension(200, 65));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);

        IssueBook.setBackground(new java.awt.Color(204, 204, 204));
        IssueBook.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        IssueBook.setForeground(new java.awt.Color(255, 0, 0));
        IssueBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sketchbook.png"))); // NOI18N
        IssueBook.setText("Issue Book");
        IssueBook.setPreferredSize(new java.awt.Dimension(200, 65));
        IssueBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssueBookActionPerformed(evt);
            }
        });
        jPanel1.add(IssueBook);

        btnReturnBook.setBackground(new java.awt.Color(204, 204, 204));
        btnReturnBook.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnReturnBook.setForeground(new java.awt.Color(255, 0, 0));
        btnReturnBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/return-box.png"))); // NOI18N
        btnReturnBook.setText("Return Book");
        btnReturnBook.setPreferredSize(new java.awt.Dimension(200, 65));
        btnReturnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnBookActionPerformed(evt);
            }
        });
        jPanel1.add(btnReturnBook);

        btnStatic.setBackground(new java.awt.Color(204, 204, 204));
        btnStatic.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnStatic.setForeground(new java.awt.Color(255, 0, 0));
        btnStatic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/project.png"))); // NOI18N
        btnStatic.setText("Static");
        btnStatic.setPreferredSize(new java.awt.Dimension(200, 65));
        btnStatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaticActionPerformed(evt);
            }
        });
        jPanel1.add(btnStatic);

        jButton13.setBackground(new java.awt.Color(204, 204, 204));
        jButton13.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 0, 0));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/log-out.png"))); // NOI18N
        jButton13.setText("Logout");
        jButton13.setPreferredSize(new java.awt.Dimension(200, 65));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);

        jMenu4.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/customer.png"))); // NOI18N
        jMenu4.setText("Reader");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMenu4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenu4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenu4.setPreferredSize(new java.awt.Dimension(95, 35));

        jMenuManagerReader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/customer.png"))); // NOI18N
        jMenuManagerReader.setText("Reader Manager");
        jMenuManagerReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuManagerReaderActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuManagerReader);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/open-book.png"))); // NOI18N
        jMenu5.setText("Book");
        jMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(95, 24));

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/open-book.png"))); // NOI18N
        jMenuItem1.setText("Book Manager");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/category (1).png"))); // NOI18N
        jMenu10.setText("Category");
        jMenu10.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMenu10.setPreferredSize(new java.awt.Dimension(110, 24));

        MItemManageCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/category (1).png"))); // NOI18N
        MItemManageCategory.setText("Category Manager");
        MItemManageCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemManageCategoryActionPerformed(evt);
            }
        });
        jMenu10.add(MItemManageCategory);

        jMenuBar1.add(jMenu10);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/editor.png"))); // NOI18N
        jMenu6.setText("Author");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(95, 24));

        jMenuManageAuthor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/editor.png"))); // NOI18N
        jMenuManageAuthor.setText("Author Manager");
        jMenuManageAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuManageAuthorActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuManageAuthor);

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/translate.png"))); // NOI18N
        jMenu7.setText("Tranlator");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMenu7.setPreferredSize(new java.awt.Dimension(110, 24));

        jMenuManagerTranslator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/translate.png"))); // NOI18N
        jMenuManagerTranslator.setText("Translator Manager");
        jMenuManagerTranslator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuManagerTranslatorActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuManagerTranslator);

        jMenuBar1.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/blog.png"))); // NOI18N
        jMenu8.setText("Publisher");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMenu8.setPreferredSize(new java.awt.Dimension(110, 24));

        jMenuManagerPublisher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/blog.png"))); // NOI18N
        jMenuManagerPublisher.setText("Publisher Manager");
        jMenuManagerPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuManagerPublisherActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuManagerPublisher);

        jMenuBar1.add(jMenu8);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/type (1).png"))); // NOI18N
        jMenu9.setText("Type");
        jMenu9.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMenu9.setPreferredSize(new java.awt.Dimension(95, 24));

        jMenuManageType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/type (1).png"))); // NOI18N
        jMenuManageType.setText("Type Manager");
        jMenuManageType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuManageTypeActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuManageType);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(DeskPHome)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DeskPHome)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MItemManageCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemManageCategoryActionPerformed
        // TODO add your handling code here:
        CategoryBook.CategoryView view = new CategoryView();
        view.setVisible(true);
        DeskPHome.add(view);
        view.setLocation((DeskPHome.getWidth()-view.getWidth())/2, (DeskPHome.getHeight()-view.getHeight())/2);
    }//GEN-LAST:event_MItemManageCategoryActionPerformed

    private void jMenuManageTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuManageTypeActionPerformed
        // TODO add your handling code here:
        TypeBook.TypeView view = new TypeView();
        view.setVisible(true);
        DeskPHome.add(view);
        view.setLocation((DeskPHome.getWidth()-view.getWidth())/2, (DeskPHome.getHeight()-view.getHeight())/2);
    }//GEN-LAST:event_jMenuManageTypeActionPerformed

    private void jMenuManageAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuManageAuthorActionPerformed
        // TODO add your handling code here:
        Author.AuthorView view = new AuthorView();
        view.setVisible(true);
        DeskPHome.add(view);
        view.setLocation((DeskPHome.getWidth()-view.getWidth())/2, (DeskPHome.getHeight()-view.getHeight())/2);
    }//GEN-LAST:event_jMenuManageAuthorActionPerformed

    private void jMenuManagerTranslatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuManagerTranslatorActionPerformed
        // TODO add your handling code here:
        Translator.TranslatorView view = new TranslatorView();
        view.setVisible(true);
        DeskPHome.add(view);
        view.setLocation((DeskPHome.getWidth()-view.getWidth())/2, (DeskPHome.getHeight()-view.getHeight())/2);
    }//GEN-LAST:event_jMenuManagerTranslatorActionPerformed

    private void jMenuManagerPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuManagerPublisherActionPerformed
        // TODO add your handling code here:
        PublisherView view = new PublisherView();
        view.setVisible(true);
        DeskPHome.add(view);
        view.setLocation((DeskPHome.getWidth()-view.getWidth())/2, (DeskPHome.getHeight()-view.getHeight())/2);
    }//GEN-LAST:event_jMenuManagerPublisherActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:ư
        Book.BookView view = new BookView();
        view.setVisible(true);
        DeskPHome.add(view);
        view.setLocation((DeskPHome.getWidth()-view.getWidth())/2, (DeskPHome.getHeight()-view.getHeight())/2);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void IssueBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueBookActionPerformed
        // TODO add your handling code here:
        IssueBookView view = new IssueBookView();
        view.setVisible(true);
        DeskPHome.add(view);
        view.setLocation((DeskPHome.getWidth()-view.getWidth())/2, (DeskPHome.getHeight()-view.getHeight())/2);
    }//GEN-LAST:event_IssueBookActionPerformed

    private void jMenuManagerReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuManagerReaderActionPerformed
        // TODO add your handling code here:
        ReaderView view = new ReaderView();
        view.setVisible(true);
        DeskPHome.add(view);
        view.setLocation((DeskPHome.getWidth()-view.getWidth())/2, (DeskPHome.getHeight()-view.getHeight())/2);
    }//GEN-LAST:event_jMenuManagerReaderActionPerformed

    private void btnReturnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnBookActionPerformed
        // TODO add your handling code here:
        ReturnBook.ReturnBookView view = new ReturnBookView();
        view.setVisible(true);
        DeskPHome.add(view);
        view.setLocation((DeskPHome.getWidth()-view.getWidth())/2, (DeskPHome.getHeight()-view.getHeight())/2);
    }//GEN-LAST:event_btnReturnBookActionPerformed

    private void btnStaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaticActionPerformed
        // TODO add your handling code here:
        Static.StaticView view = new StaticView();
        view.setVisible(true);
        DeskPHome.add(view);
        view.setLocation((DeskPHome.getWidth()-view.getWidth())/2, (DeskPHome.getHeight()-view.getHeight())/2);
    }//GEN-LAST:event_btnStaticActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        ReaderView view = new ReaderView();
        view.setVisible(true);
        DeskPHome.add(view);
        view.setLocation((DeskPHome.getWidth()-view.getWidth())/2, (DeskPHome.getHeight()-view.getHeight())/2);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        Book.BookView view = new BookView();
        view.setVisible(true);
        DeskPHome.add(view);
        view.setLocation((DeskPHome.getWidth()-view.getWidth())/2, (DeskPHome.getHeight()-view.getHeight())/2);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DeskPHome;
    private javax.swing.JButton IssueBook;
    private javax.swing.JMenuItem MItemManageCategory;
    private javax.swing.JButton btnReturnBook;
    private javax.swing.JButton btnStatic;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuManageAuthor;
    private javax.swing.JMenuItem jMenuManageType;
    private javax.swing.JMenuItem jMenuManagerPublisher;
    private javax.swing.JMenuItem jMenuManagerReader;
    private javax.swing.JMenuItem jMenuManagerTranslator;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
